#! GolangCI-Lint

# Options for analysis running.
run:
  # The default concurrency value is the number of available CPU.
  #concurrency: 4

  # Timeout for analysis, e.g. 30s, 5m.
  #timeout: 1m

  # Exit code when at least one issue was found.
  #issues-exit-code: 1

  # Include test files or not.
  tests: true

  # List of build tags, all linters use it.
  #build-tags: []

  # Which dirs to skip: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path,
  # including the path prefix if one is set.
  # Default value is empty list,
  # but default dirs are skipped independently of this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  #skip-dirs: []

  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  #skip-dirs-use-default: true

  # Which files to skip: they will be analyzed, but issues from them won't be reported.
  # Default value is empty list,
  # but there is no need to include all autogenerated files,
  # we confidently recognize autogenerated files.
  # If it's not please let us know.
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  #skip-files:

  # If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #
  # Allowed values: readonly|vendor|mod
  # By default, it isn't set.
  #modules-download-mode:

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  #allow-parallel-runners: false

  # Define the Go version limit.
  # Mainly related to generics support since go1.18.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.18
  #go: '1.19'

# output configuration options
output:
  # Format: colored-line-number|line-number|json|colored-tab|tab|checkstyle|code-climate|junit-xml|github-actions|teamcity
  #
  # Multiple can be specified by separating them by comma, output can be provided
  # for each of them by separating format name and path by colon symbol.
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  # Example: "checkstyle:report.xml,json:stdout,colored-line-number"
  #
  format: colored-line-number

  # Print lines of code with issue.
  print-issued-lines: true

  # Print linter name in the end of issue text.
  print-linter-name: true

  # Make issues output unique by line.
  #uniq-by-line: true

  # Add a prefix to the output file references.
  # Default is no prefix.
  #path-prefix: ""

  # Sort results by: filepath, line and column.
  sort-results: true

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    check-type-assertions: false
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    check-blank: true
    # To disable the errcheck built-in exclude list.
    # See `-excludeonly` option in https://github.com/kisielk/errcheck#excluding-functions for details.
    disable-default-exclusions: false
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions: []

  gosimple:
    # Sxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["*"]

  govet:
    # Report about shadowed variables.
    check-shadowing: true
    # Settings per analyzer.
    settings:
      # Analyzer name, run `go tool vet help` to see all analyzers.
      #printf:
      # Comma-separated list of print function names to check (in addition to default, see `go tool vet help printf`).
      #funcs: []
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        strict: false
      unusedresult:
        # Comma-separated list of functions whose results must be used
        # (in addition to defaults context.WithCancel,context.WithDeadline,context.WithTimeout,context.WithValue,
        # errors.New,fmt.Errorf,fmt.Sprint,fmt.Sprintf,sort.Reverse)
        # Default []
        funcs: []
        # Comma-separated list of names of methods of type func() string whose results must be used
        # (in addition to default Error,String)
        # Default []
        stringmethods: []
    # Enable all analyzers.
    # Default: false
    enable-all: true
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    disable:
      - fieldalignment

  staticcheck:
    # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["*"]

  stylecheck:
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["*"]
    # https://staticcheck.io/docs/configuration/options/#initialisms
    initialisms:
      - "ACL"
      - "API"
      - "ASCII"
      - "CPU"
      - "CSS"
      - "DNS"
      - "EOF"
      - "GUID"
      - "HTML"
      - "HTTP"
      - "HTTPS"
      - "ID"
      - "IP"
      - "JSON"
      - "QPS"
      - "RAM"
      - "RPC"
      - "SLA"
      - "SMTP"
      - "SQL"
      - "SSH"
      - "TCP"
      - "TLS"
      - "TTL"
      - "UDP"
      - "UI"
      - "GID"
      - "UID"
      - "UUID"
      - "URI"
      - "URL"
      - "UTF8"
      - "VM"
      - "XML"
      - "XMPP"
      - "XSRF"
      - "XSS"
      - "SIP"
      - "RTP"
      - "AMQP"
      - "DB"
      - "TS"

linters:
  disable-all: true

  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - stylecheck
    - unused

  # Run only fast linters from enabled linters set (first run won't be fast)
  fast: false

