// Code generated by "stringer -trimprefix Token -type Token"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-1]
	_ = x[TokenComment-2]
	_ = x[TokenName-3]
}

const _Token_name = "EOFCommentName"

var _Token_index = [...]uint8{0, 3, 10, 14}

func (i Token) String() string {
	i -= 1
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
